import { Document, Packer, Paragraph, TextRun } from "docx";
import { saveAs } from "file-saver";

const removeCitations: RegExp = /{% citation items=.*?%}/g;

function removeNumbersFromStringUsingRegex( input:string):string {
    return input.replace(removeCitations, "");
}

export const generateWordDocument = (content:string) => {
  
  const trimmedContent = removeNumbersFromStringUsingRegex(content);
  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            children: [
              new TextRun(trimmedContent),              
              new TextRun({
                text: "\n\n Generated by Azure Chat. Please note that AI generated content must be reviewed by a real person.",
                break: 1,
                bold: true,
              }),
            ],
          }),
        ],
      },
    ],
  });

  // Pack the document into a blob and save it
  Packer.toBlob(doc).then((blob) => {
    saveAs(blob, "azure-chat.docx");
  });
};
