import { saveAs } from "file-saver";
import { unified } from "unified";
import markdown from "remark-parse";
import docx from "remark-docx";
import  remarkGfm  from "remark-gfm";

const removeCitations: RegExp = /{% citation items=.*?%}/g;

function removeNumbersFromStringUsingRegex( input:string):string {
    return input.replace(removeCitations, "");
}

const processor = unified()
  .use(markdown)
  .use(remarkGfm)
  .use(docx, { output: "blob" });

//const headingMarkDown = "![NSW Government](https://www.nsw.gov.au/themes/custom/dcs_theme/favicons/sets/national/logo.svg)";
const naviWarning = "\n\n **Generated by Azure Chat. Please note that AI generated content must be reviewed by a real person.** \n\n";

export const generateWordDocument = async (content:string) => {

  console.log("content from generateWordDocument");
  console.log(content);
  const fullMarkdown = removeNumbersFromStringUsingRegex(content)  + naviWarning;
  const doc = await processor.process(fullMarkdown);
  const blob = await doc.result;

  saveAs(blob, "example.docx");
}

